### ISSUE TITLE
Add command-reply config

### ISSUE THREAD

**Issue by vladyslav-fenchak** [Clariteia/minos_microservice_networks#117]
```yaml
command-reply:
    broker: localhost
    port: 9092
    items:
        - name: AddOrderReply
          controller: minos.services.OrderService
          action: add_order
        - name: DeleteOrderReply
          controller: minos.services.OrderService
          action: delete_order
        - name: UpdateOrderReply
          controller: minos.services.OrderService
          action: update_order
        - name: GetOrderReply
          controller: minos.service.OrderService
          action: get_order
    queue:
        database: order_db
        user: minos
        password: min0s
        host: localhost
        port: 5432
        records: 10
        retry: 2
```
