### ISSUE TITLE
Minos Config yaml file must be complete

### ISSUE THREAD

**Issue by vladyslav-fenchak** [Clariteia/minos_microservice_networks#59]
The *.yaml file must be modified.
The next property must be deleted from events/commands: 
```yaml
database:
        path: ./tests/local_db.lmdb
        name: database_events_test
```
This modification is to align with the new version of minos_microservice_common and also because the PostgreSQL database will be used instead of lmdb.
